2025-08-21 00:34:15,234 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/foliage_report/listar_reportes/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:34:36,640 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/foliage_report/listar_reportes/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:34:37,099 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/foliage_report/listar_reportes/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:34:37,448 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/foliage_report/listar_reportes/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:34:37,833 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/foliage_report/listar_reportes/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:38:17,769 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:38:20,253 - ERROR - Error occurred: expected token 'end of statement block', got ':'
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/templates/default/partials/sidebar.j2", line 83, in template
    "name": "Veg Index",
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got ':'

2025-08-21 00:53:41,373 - ERROR - Error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Method: GET, Path: /favicon.ico, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Dnt: 1
Sec-Ch-Ua-Mobile: ?0
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: image
Referer: http://localhost:6084/dashboard/agrovista/hello
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-08-21 01:22:30,549 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:22:33,050 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:23:13,825 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:23:14,838 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:23:15,305 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:23:15,668 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:23:15,938 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:23:17,204 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:35,581 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:37,068 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:37,652 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:38,157 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:38,423 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:38,596 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/dashboard/clients
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:26:42,245 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:28:46,471 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:28:58,484 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:28:59,127 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Cache-Control: max-age=0
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:29:03,693 - ERROR - Error occurred: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?
Method: GET, Path: /dashboard, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Dnt: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Referer: http://localhost:6084/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/core/controller.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/core/web_routes.py", line 149, in dashboard
    render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/app/core/templates/dashboard/welcome.j2", line 1, in top-level template code
    {% extends "base.j2" %}
  File "/app/app/templates/default/base.j2", line 27, in top-level template code
    {% include 'partials/sidebar.j2' %}
  File "/app/app/templates/default/partials/sidebar.j2", line 82, in top-level template code
    {% set vgindex_menu = {
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'agrovista.hello'. Did you mean 'foliage_report.vista_report' instead?

2025-08-21 01:50:28,988 - ERROR - Error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Method: GET, Path: /.well-known/appspecific/com.chrome.devtools.json, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Pragma: no-cache
Cache-Control: no-cache
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-08-21 01:53:04,987 - ERROR - Error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Method: GET, Path: /.well-known/appspecific/com.chrome.devtools.json, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Pragma: no-cache
Cache-Control: no-cache
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-08-21 01:56:27,904 - ERROR - Error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Method: GET, Path: /.well-known/appspecific/com.chrome.devtools.json, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Pragma: no-cache
Cache-Control: no-cache
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-08-21 01:57:44,724 - ERROR - Error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Method: GET, Path: /.well-known/appspecific/com.chrome.devtools.json, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Pragma: no-cache
Cache-Control: no-cache
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-08-21 01:57:48,179 - ERROR - Error occurred: 500 Internal Server Error: processing error
Method: POST, Path: /api/agrovista/upload, Headers: Host: localhost
X-Real-Ip: 172.20.0.1
X-Forwarded-For: 172.20.0.1
Accept-Charset: utf-8
Connection: close
Content-Length: 42987400
Pragma: no-cache
Cache-Control: no-cache
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Sec-Ch-Ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
Dnt: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryLWHtgYHYEtukwTWv
Sec-Ch-Ua-Mobile: ?0
Accept: */*
Origin: http://localhost:6084
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:6084/dashboard/agrovista/
Accept-Language: es-CO,es-US;q=0.9,es;q=0.8,en;q=0.7
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MjM1MDM0LTM0NDUtNDJkMS04YThlLWEyYjAyNDMzMmQ4YiJ9.vpMxJWot9lDuRt6rDawENJsYp-__pDbfoxkjyFd13wM; gitea_incredible=tbOscUgbQF%3Acb2606af5456766e2036aa86b75422ea8bb35a3e2a5fe154e2668100d3ae50b6; i_like_gitea=c61100143c605b57; lang=es-ES; _csrf=gEbX6sObCzsck4Pt7Brb3g_33F06MTc1NTczMjYzNzE5MDU0MTk2NQ; adminer_key=20fbc70b57aed44036a73e1d59ae8445; adminer_version=5.3.0; adminer_sid=ec9cae93cc339bf2938436c43d70f0b7; adminer_settings=vendor-server-db%3DMariaDB; access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NTczNTQ3NywianRpIjoiNzQ5YmEwNjQtOGQ3My00NmMyLTg2OGYtZjQyMGRhMWZlZDg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkI1MERDMjZFIiwibmJmIjoxNzU1NzM1NDc3LCJjc3JmIjoiZmY4Mzg4NzItYTUwMi00YjQzLWJiMDctMGQwOTAzNjhjZWM2IiwiZXhwIjoxNzU1OTA4Mjc3LCJpZCI6IkI1MERDMjZFIiwidXNlcm5hbWUiOiJtZXJsaW4iLCJlbWFpbCI6Im1lcmxpbkBzeXN0ZW0ubG9jYWwiLCJvcmdhbml6YXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Ik9yZ2FuaXphY2lcdTAwZjNuIFByaW5jaXBhbCJ9XSwicm9sIjoiYWRtaW5pc3RyYXRvciJ9.JWiZmReNT8RxsuztO1g-t_wi4AX3n0KpmmNttRjMJpc; csrf_access_token=ff838872-a502-4b43-bb07-0d090368cec6; csrf_refresh_token=bd8fa197-a722-484c-ba8a-7de16d66f274

, Body: 
Traceback: Traceback (most recent call last):
  File "/app/app/modules/agrovista/api_routes.py", line 30, in upload
    meta = process_upload(request.files.get("file"))
  File "/app/app/modules/agrovista/controller.py", line 14, in process_upload
    ndvi = compute_ndvi(tmp_path)
  File "/app/app/modules/agrovista/helpers.py", line 27, in compute_ndvi
    return np.round(ndvi.filled(np.nan), 2)
AttributeError: 'numpy.ndarray' object has no attribute 'filled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/modules/agrovista/api_routes.py", line 35, in upload
    abort(500, description="processing error")
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: processing error

